### ISSUE TITLE
TODO liste

### ISSUE THREAD

**Issue by A-Louarn** [TheMrNomis/KiWi-calendar#1]
# TODO List
## global
- [x] use categories
- [x] https://stackoverflow.com/questions/920353/can-i-bind-an-array-to-an-in-condition
## Event Page
- [x] Modify map : nominatim
- [x] connect function
- [x] Edit page : Categories 
- [x] Edit page : Delete event 
## About page
- [x] About page
- [x] Add license
## day page
- [x] link to index.php when click on one of the logos
- [x] "en savoir plus" ne redirige pas vers la page event.php
## Index Page
- [x] ENT
- [x] Afficher les évènements de quelques heures
- [x] Problème avec l'affichage du mois quand on zoom
## Add Event
- [x] Add categories
- [x] Rendre certaines données obligatoires
- [x] Changer la langue du calendrier
- [x] When the event is added, go to the index page
- [x] Edit event (need test)
- [x] affichage des catégories un peu plus nice
- [x] supprimer les espaces vides au début de "description"
- [x] changer la gestion des dates (mettre des listes déroulantes)
## V1
- [x] Need 1 checkbox
- [ ] Sync with others calendars
- [x] The map is slow
- [x] flexbox
- [x] pouvoir déselectionner plusieurs checkbox
- [x] Connect to the ENT
- [ ] Clean code (115 bonnes pratiques)
- [x] Code au W3C validator
- [x] Push to server
